# cloudbuild.yaml - Automatic deployment from GitHub
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nhl-prediction-gpt', '-f', 'Dockerfile.cloudrun', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nhl-prediction-gpt']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'nhl-prediction-gpt'
      - '--image'
      - 'gcr.io/$PROJECT_ID/nhl-prediction-gpt'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300s'
      - '--concurrency'
      - '80'
      - '--max-instances'
      - '10'
  - '--set-env-vars'
  - 'GIT_SHA=$COMMIT_SHA,APP_VARIANT=NHL,ODDS_SPORT_KEYS=icehockey_nhl,icehockey_nhl_preseason'

options:
  logging: CLOUD_LOGGING_ONLY