openapi: 3.1.1
info:
  title: NHL Prediction API
  version: 1.0.0
  description: |
    Predict NHL game outcomes with model probabilities and simple analysis.
    This spec is tailored for use as a Custom GPT Action.
servers:
  - url: https://nhl-prediction-gpt-455856529947.us-central1.run.app
paths:
  /health:
    get:
      summary: Health check for the model service
      operationId: getHealth
      responses:
        '200':
          description: Service status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

  /teams:
    get:
      summary: Get all NHL teams organized by division
      operationId: getNHLTeams
      responses:
        '200':
          description: NHL teams by division
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeamsResponse'

  /predict:
    get:
      summary: Predict outcome for an NHL matchup
      operationId: predictMatchup
      parameters:
        - in: query
          name: home
          required: true
          description: Home team NHL abbreviation (e.g., TOR, BOS)
          schema:
            $ref: '#/components/schemas/TeamAbbr'
        - in: query
          name: away
          required: true
          description: Away team NHL abbreviation (e.g., MTL, NYR)
          schema:
            $ref: '#/components/schemas/TeamAbbr'
      responses:
        '200':
          description: Prediction result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PredictResponse'
        '400':
          description: Missing or invalid parameters
        '500':
          description: Internal error

  /odds:
    get:
      summary: Get current live odds for NHL games
      operationId: getLiveOdds
      parameters:
        - in: query
          name: home
          required: false
          description: Home team NHL abbreviation (optional - if provided with away, gets odds for specific game)
          schema:
            $ref: '#/components/schemas/TeamAbbr'
        - in: query
          name: away
          required: false
          description: Away team NHL abbreviation (optional - if provided with home, gets odds for specific game)
          schema:
            $ref: '#/components/schemas/TeamAbbr'
      responses:
        '200':
          description: Live odds data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OddsResponse'
        '500':
          description: Internal error

components:
  schemas:
    TeamAbbr:
      type: string
      description: Official NHL team abbreviation
      example: TOR
      pattern: '^(ANA|ARI|BOS|BUF|CGY|CAR|CHI|COL|CBJ|DAL|DET|EDM|FLA|LAK|MIN|MTL|NSH|NJD|NYI|NYR|OTT|PHI|PIT|SJS|SEA|STL|TBL|TOR|VAN|VGK|WSH|WPG)$'

    TeamsResponse:
      type: object
      properties:
        Atlantic:
          type: array
          items:
            type: string
        Metropolitan:
          type: array
          items:
            type: string
        Central:
          type: array
          items:
            type: string
        Pacific:
          type: array
          items:
            type: string

    HealthResponse:
      type: object
      properties:
        status:
          type: string
          description: Overall service status
        models_loaded:
          type: object
          properties:
            with_odds:
              type: boolean
            without_odds:
              type: boolean
        memory_usage_mb:
          type: number
          format: float
        model_files:
          type: array
          items:
            type: object
            properties:
              filename:
                type: string
              exists:
                type: boolean
              size_mb:
                type: number
                format: float

    PredictResponse:
      type: object
      properties:
        home_team:
          $ref: '#/components/schemas/TeamAbbr'
        away_team:
          $ref: '#/components/schemas/TeamAbbr'
        predictions:
          type: object
          properties:
            home_win_probability:
              type: number
              format: float
            away_win_probability:
              type: number
              format: float
            confidence_interval:
              type: array
              items:
                type: number
                format: float
            prediction:
              type: string
              description: Team predicted to win
        features_used:
          type: array
          items:
            type: string
        model_type:
          type: string
          description: Model used for prediction (with_odds or without_odds)

    OddsResponse:
      type: object
      properties:
        total_games:
          type: integer
          description: Number of games with odds available
        games:
          type: array
          items:
            type: object
            properties:
              game:
                type: string
                description: Game matchup (e.g., "BOS @ TOR")
              odds:
                type: object
                properties:
                  spread_line:
                    type: number
                    format: float
                  total_line:
                    type: number
                    format: float
                  home_moneyline:
                    type: number
                  away_moneyline:
                    type: number
                  source:
                    type: string
        last_updated:
          type: string
          format: date-time
          description: When the odds were last updated
