services:
  - type: web
    name: nhl-prediction-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py app_nhl:app
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: WEB_CONCURRENCY
        value: 1
      - key: PORT
        generateValue: true
    autoDeploy: true
    branch: main